 const constant = {
    darkTheme : "DARKTHEME",
    lightTheme : "LIGHTTHEME",
    gridHeader :  "GRIDHEADER",
    gridElements : "GRIDELEMENTS" ,
    name : "GRIDHEADER",
    textSizeLarge : "LARGE",
    textSizeMedium : "MEDUIM",
    textSizeSmall : "SMALL",
    fontStyleNormal : "NORMAL",
    fontStyleItalic : "ITALIC",
    fontStyleOblique: "OBILIQUE",
    textColor : "TEXTCOLOR",
    backgroundColor : "BACKGROUNDCOLOR",
    defaultTextColor : "DEFAULTTEXTCOLOR",
    defaultBackgroundColor : "DEFAULTBACKGROUNDCOLOR",
    cityCheckBox:"City",
    priceCheckBox:"Price",
    colorCheckBox:"Color",
    startdateCheckBox:"Start Date",
    endDateCheckBox:"End Date",
    statusCheckBox:"Status",
 }

 export default constant;